### ISSUE TITLE
Doesn't recognize c.doxygen as C syntax

### ISSUE THREAD

**Issue by jayPare** [mgedmin/chelper.vim#1]
Used your example to test this and nothing in the satus line. How should I debug this?

**Comment by mgedmin** [comment]
Let's start with this one: what does `:echo CTagInStatusLine()` print?

**Comment by mgedmin** [comment]
Now that I'm not on a phone, I can be more verbose.  Here are what steps I would use to debug this kind of problem:

- was this Vim compiled with Python support, i.e. does `:echo has('python') || has('python3')` print a `1`?
- was the script loaded, i.e. can you see `chelper.vim` in the output of `:scriptnames`?
- is the statusline configured to include `%{CTagInStatusLine()}` in it -- check with `:echo &statusline`?
- does the plugin parse the function name correctly -- check with `:echo CTagInStatusLine()`?

If the first three tests pass but the last one fails, I'd like to see the C source code that my hacky parser couldn't handle.

**Comment by jayPare** [comment]
That's the situation here, the first three pass, but not the third one. Code is under NDA, but I will try to find something where I could replicate this.

**Comment by jayPare** [comment]
You could try with some Intel Ethernet code, I seems to be able to reproduce this with it:

[https://github.com/andriymoroz/IES](url)

I tried `fm_api_stats.c` in `src/api`.

**Comment by mgedmin** [comment]
I've found a few problems with my simplistic parser:
- it would consider the line consisting of `{` to be the beginning of the new function, rather than the line that contained the function name
- it wouldn't recognize the ends of functions, because it expected a line consisting solely of a `}` without any trailing comments
- there could be a Python traceback about unorderable types near the bottom of the file if your Vim was using Python 3, because of the previous bug
- when it saw `int *foo(...)`, my parser would think `*foo` was the name of the function

I've fixed those now.

Other than that, I get tags in `fm_api_stats.c`:

![ekrano nuotrauka is 2017-06-20 15-08-54](https://user-images.githubusercontent.com/159967/27332394-64793200-55ca-11e7-9986-a9b80c60e684.png)

I've also added a function to ease debugging -- `:call ShowCTags()`:

![ekrano nuotrauka is 2017-06-20 15-15-36](https://user-images.githubusercontent.com/159967/27332649-5ae8577e-55cb-11e7-8ee3-b0e70e88850f.png)

I'd like to see if you can reproduce my results on that file!

**Comment by jayPare** [comment]
I got the same output as you when I use `:call ShowCTags()`: 
![image](https://user-images.githubusercontent.com/8458193/27337039-49e40ec2-559f-11e7-8e8b-9830cf42aa9b.png)



But `:echo CTagInStatusLine()` is still giving me nothing.

`:echo CTagInStatusLine()` is giving me this:

`%<%f %h%m%r %1*%{CTagInStatusLine()}%*%=%-14.(%l,%c%V%) %P`

**Comment by mgedmin** [comment]
Ooh, this is getting more and more interesting!

What's your vim version?  Does it support the 'CursorMoved' autocommand, which was introduced in 7.0.195?

**Comment by jayPare** [comment]
I'm running 8.0 and CursordMoved seems to be supported:

![image](https://user-images.githubusercontent.com/8458193/27343069-d73bc84a-55af-11e7-9867-d2e152ba5793.png)

**Comment by jayPare** [comment]
Found the problem. It resides in the fact I'm using doxygen. Therefore, the command `b:current_syntax` returns `c.doxygen`. I forked your repo, made the change and created the pull request. I will delete my forked repo after. I think this is the way to proceed with GitHub? If not let me know. :)

**Comment by mgedmin** [comment]
Good catch!

Your pull request looks right to me, although I think I'll update it to accept `c.<anything>`, not just `c.doxygen`.

(The way Vim allows you to mix multiple filetypes into one by separating them with dots is something I'm not very familiar with!)
